name: 'Terraform'

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  workflow_dispatch:

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET }}
  AWS_DEFAULT_REGION: eu-north-1

defaults:
  run:
    working-directory: terraform

jobs:
  plan:
    name: Terraform Plan
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    steps:
      - uses: actions/checkout@v4

      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.14.0

      - name: Ensure Terraform state bucket exists
        working-directory: '.'
        run: |
          aws s3api head-bucket --bucket snapsoft-homework-tf-state-tsz 2>/dev/null || \
          aws s3api create-bucket \
            --bucket snapsoft-homework-tf-state-tsz \
            --region eu-north-1 \
            --create-bucket-configuration LocationConstraint=eu-north-1

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: terraform plan -no-color

  apply:
    name: Terraform Apply
    runs-on: ubuntu-latest
    if: github.event_name != 'pull_request'
    steps:
      - uses: actions/checkout@v4

      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.14.0

      - name: Ensure Terraform state bucket exists
        working-directory: '.'
        run: |
          aws s3api head-bucket --bucket snapsoft-homework-tf-state-tsz 2>/dev/null || \
          aws s3api create-bucket \
            --bucket snapsoft-homework-tf-state-tsz \
            --region eu-north-1 \
            --create-bucket-configuration LocationConstraint=eu-north-1

      - name: Terraform Init
        run: terraform init

      - name: Terraform Apply
        run: terraform apply -auto-approve
